import { themePresets } from "../core/defaults.js";

// A fictional restaurant: change these values to create a client site.
// Keep private credentials in server environment variables, never in this file.
export const siteConfig = {
  activePreset: "casual-modern",
  themePresets,
  routes: [
    "/",
    "/our-cuisine/",
    "/our-drinks/",
    "/locations/",
    "/location/",
    "/reserve/",
    "/privacy-policy/",
  ],
  brand: {
    name: "Casa Oliva",
    sourceName: "Mott 32",
    legalName: "Casa Oliva · restaurante de ejemplo",
    slug: "casa-oliva",
    language: "es",
    locale: "es_ES",
    market: "Spain",
    logo: "",
    footerLogo: "",
    email: "hola@example.com",
    careersEmail: "equipo@example.com",
    privacyEmail: "privacidad@example.com",
    phone: "",
    cuisine: "Mediterranean",
    priceRange: "€€",
    description:
      "Cocina de temporada, una mesa compartida y tiempo para disfrutar.",
  },
  navigation: {
    drawer: [
      { href: "/", label: "Inicio" },
      { href: "/our-cuisine/", label: "Nuestra cocina" },
      { href: "/our-drinks/", label: "Bebidas" },
      { href: "/locations/", label: "Restaurantes" },
      { href: "/reserve/", label: "Reservar" },
    ],
    footer: [
      { href: "/locations/", label: "Restaurantes" },
      { href: "/our-cuisine/", label: "Carta" },
      { href: "/our-drinks/", label: "Bebidas" },
      { href: "/privacy-policy/", label: "Privacidad" },
      { href: "mailto:{email}", label: "{email}" },
    ],
  },
  socialLinks: [],
  reservation: { primaryLabel: "Reservar", fallbackHref: "/reserve/" },
  locations: [
    {
      slug: "madrid",
      name: "Madrid",
      han: "",
      region: "España",
      status: "open",
      address: "Calle de ejemplo, 1",
      postalAddress: {
        addressLocality: "Madrid",
        addressRegion: "Madrid",
        addressCountry: "ES",
        postalCode: "28001",
      },
      image: "/assets/oliva-interior.jpg",
      hours: "Martes a domingo · 13:00–16:00 y 20:00–23:00",
      phone: "",
      email: "{email}",
      reserve: "mailto:{email}?subject=Reserva",
      reservationProvider: "Email",
      cuisinePdf: "",
      drinksPdf: "",
      menuNote: "Una carta que cambia con la temporada.",
      intro: "Un espacio para encontrarse alrededor de una buena mesa.",
      copy: "Producto de temporada, cocina honesta y una hospitalidad atenta. Un comedor cálido donde la sobremesa también forma parte del plan.",
    },
  ],
  menu: {
    categories: {
      seasonal: "De temporada",
      signature: "Especialidades",
      dessert: "Postres",
      wine: "Vinos",
      cocktail: "Sin alcohol",
    },
    items: [
      {
        id: "huerta",
        kind: "food",
        category: "seasonal",
        title: "La huerta de temporada",
        description: "Verduras asadas, hierbas frescas y aceite de oliva.",
        image: "/assets/oliva-huerta.jpg",
        locations: ["madrid"],
        price: "14 €",
        allergens: [],
        dietary: ["vegetariano"],
      },
      {
        id: "arroz",
        kind: "food",
        category: "signature",
        title: "Arroz de la casa",
        description: "Arroz meloso de setas con caldo de verduras.",
        image: "/assets/oliva-arroz.jpg",
        locations: ["madrid"],
        price: "22 €",
        allergens: ["apio"],
        dietary: [],
      },
      {
        id: "postre",
        kind: "food",
        category: "dessert",
        title: "El final dulce",
        description:
          "Pera e higos asados con crema de vainilla y un toque de naranja.",
        image: "/assets/oliva-postre.jpg",
        locations: ["madrid"],
        price: "8 €",
        allergens: ["leche"],
        dietary: [],
      },
      {
        id: "vino",
        kind: "drinks",
        category: "wine",
        title: "Vino por copas",
        description: "Una selección que acompaña nuestra cocina.",
        image: "/assets/oliva-vino.jpg",
        locations: ["madrid"],
        price: "6 €",
        allergens: ["sulfitos"],
        dietary: [],
      },
      {
        id: "citrico",
        kind: "drinks",
        category: "cocktail",
        title: "Cítrico de la casa",
        description: "Cítricos, hierbabuena y agua con gas.",
        image: "/assets/oliva-citrico.jpg",
        locations: ["madrid"],
        price: "7 €",
        allergens: [],
        dietary: ["sin alcohol"],
      },
    ],
  },
  content: {
    kind: "generic",
    titles: {
      "/locations/": "Nuestros restaurantes",
      "/reserve/": "Tu próxima mesa",
      "/privacy-policy/": "Privacidad",
    },
    home: {
      hero: "/assets/oliva-interior.jpg",
      eyebrow: "Cocina · Encuentro · Temporada",
      tagline: "El placer de compartir la mesa.",
      introEyebrow: "Nuestra manera de hacer",
      title: "Lo bueno empieza en el origen",
      locationsEyebrow: "Un lugar para quedarse",
      galleryEyebrow: "De la cocina a la mesa",
      galleryTitle: "Un primer bocado",
      paragraphs: [
        "Elegimos productos de temporada y los cocinamos con respeto. Queremos que cada visita sea una ocasión para parar, conversar y disfrutar.",
        "La huerta, el arroz y el aceite de oliva marcan nuestra manera de cocinar. En la mesa, todo invita a compartir y a alargar la sobremesa.",
      ],
    },
    food: {
      image: "/assets/oliva-huerta.jpg",
      eyebrow: "Producto · Origen · Temporada",
      title: "Nuestra cocina",
      description:
        "Sabores de temporada, recetas de la casa y una carta para compartir.",
    },
    drinks: {
      image: "/assets/oliva-citrico.jpg",
      eyebrow: "Una copa y una buena conversación",
      title: "Algo para brindar",
      description:
        "Vinos, bebidas sin alcohol y pequeños descubrimientos para acompañar la mesa.",
    },
    events: {
      image: "/assets/oliva-interior.jpg",
      eyebrow: "Juntos, alrededor de la mesa",
      title: "Hay ocasiones que merecen una buena mesa",
      copy: "Una comida entre amigos, un cumpleaños o una cena en familia. Cuéntanos qué tienes en mente y prepararemos contigo la ocasión.",
      href: "mailto:{email}?subject=Una%20mesa%20en%20Casa%20Oliva",
      label: "Cuéntanos tu idea",
    },
    editorial: {
      "/privacy-policy/": [
        {
          title: "Responsable y contacto",
          body: "Esta es una política de ejemplo para {brand}. Antes de publicar, incorpora la identidad y los datos de contacto del responsable. Puedes escribir a {privacyEmail}.",
        },
        {
          title: "Lista de invitados",
          body: "Si te apuntas a nuestra lista con tu consentimiento, guardaremos tu correo para enviarte noticias e invitaciones. Puedes solicitar la baja escribiendo a {privacyEmail}.",
        },
        {
          title: "Reservas y preferencias",
          body: "Las reservas se tramitan a través del contacto o proveedor indicado. El navegador conserva tu elección de restaurante y tus preferencias. Revisa este texto y adapta los plazos de conservación y los proveedores antes de publicar.",
        },
      ],
    },
  },
  vip: {
    enabled: true,
    delayMs: 12000,
    scrollRatio: 0.6,
    reopenDays: 7,
    variants: [
      {
        id: "invitados",
        image: "/assets/oliva-interior.jpg",
        eyebrow: "Nuestra mesa",
        title: "Sé parte de la casa",
        copy: "Recibe noticias, menús especiales e invitaciones.",
        fieldLabel: "Email",
        cta: "Apuntarme",
      },
    ],
  },
  newsletter: {
    endpoint: "/api/newsletter",
    consentLabel:
      "Quiero recibir noticias e invitaciones por correo electrónico.",
    privacyLabel: "Política de privacidad",
    pendingMessage: "Guardando…",
    successMessage: "Ya estás en la lista. ¡Gracias!",
    errorMessage: "No hemos podido guardar tu correo. Inténtalo de nuevo.",
    unavailableMessage:
      "Las inscripciones no están disponibles en este momento.",
  },
  labels: {
    all: "Todos",
    ourLocations: "Nuestra casa",
    allLocations: "Restaurantes",
    visit: "Visitar",
    status: "Estado",
    hours: "Horario",
    open: "Abierto",
    comingSoon: "Próxima apertura",
    regions: "Regiones",
    menuFilters: "Filtros de carta",
    exploreMenu: "Explora nuestra carta",
    menuItem: "Detalle del plato",
    close: "Cerrar",
    viewMenu: "Ver la carta",
    viewDrinks: "Ver las bebidas",
  },
  seo: {
    baseUrl: "https://casa-oliva.example.com",
    indexable: false,
    sameAs: [],
    pages: {
      "/": {
        title: "{brand} | Cocina de temporada",
        description: "Cocina de temporada y el placer de compartir la mesa.",
        image: "/assets/oliva-interior.jpg",
      },
      "/our-cuisine/": {
        title: "Nuestra cocina | {brand}",
        description: "Descubre nuestra carta de temporada.",
        image: "/assets/oliva-huerta.jpg",
      },
      "/our-drinks/": {
        title: "Bebidas | {brand}",
        description: "Vinos y bebidas para acompañar tu mesa.",
        image: "/assets/oliva-citrico.jpg",
      },
      "/locations/": {
        title: "Restaurantes | {brand}",
        description: "Direcciones, horarios y contacto.",
        image: "/assets/oliva-interior.jpg",
      },
      "/reserve/": {
        title: "Reservar | {brand}",
        description: "Encuentra tu restaurante y reserva una mesa.",
        image: "/assets/oliva-interior.jpg",
      },
      "/privacy-policy/": {
        title: "Privacidad | {brand}",
        description: "Información sobre tus datos y preferencias.",
        image: "/assets/oliva-interior.jpg",
      },
    },
  },
};
