export const siteConfig = {
  activePreset: "fine-dining",
  brand: {
    name: "Mott 32",
    sourceName: "Mott 32",
    legalName: "Premium Restaurant Group",
    slug: "premium-restaurant",
    description:
      "Luxury restaurant website template with reservations, location-aware menus, galleries and local SEO.",
    logo: "/assets/mott32-main-logo.svg",
    footerLogo: "/assets/mott32-footer-logo.svg",
    email: "reservations@example.com",
    careersEmail: "careers@example.com",
    privacyEmail: "privacy@example.com",
    phone: "+34 900 000 000",
    cuisine: "Chinese",
    priceRange: "€€€€",
    locale: "es_ES",
    market: "Spain",
  },
  themePresets: {
    "fine-dining": {
      label: "Fine Dining / Luxury",
      cssVars: {
        "--blue": "#0a253d",
        "--blue-deep": "#031017",
        "--gold": "#a4916d",
        "--gold-light": "#c6b282",
        "--black": "#02080b",
      },
    },
    "casual-modern": {
      label: "Casual Modern",
      cssVars: {
        "--blue": "#183b34",
        "--blue-deep": "#081714",
        "--gold": "#d2ad63",
        "--gold-light": "#ebc981",
        "--black": "#050706",
      },
    },
    "bar-night": {
      label: "Bar / Cocktail / Night",
      cssVars: {
        "--blue": "#151429",
        "--blue-deep": "#070713",
        "--gold": "#b78661",
        "--gold-light": "#d9aa7e",
        "--black": "#05040a",
      },
    },
  },
  navigation: {
    footer: [
      { href: "/locations/", label: "All Locations" },
      { href: "/sustainability/", label: "Sustainability" },
      { href: "/careers/", label: "Careers" },
      { href: "/founders/", label: "Founders" },
      { href: "/our-cuisine/", label: "Our Food" },
      { href: "/our-drinks/", label: "Our Drinks" },
      { href: "/awards-media/", label: "Awards & Media" },
      { href: "/privacy-policy/", label: "Privacy policy" },
      { href: "mailto:{email}", label: "{email}" },
    ],
    drawer: [
      { href: "/", label: "Home" },
      { href: "/our-cuisine/", label: "Our Cuisine" },
      { href: "/our-drinks/", label: "Our Drinks" },
      { href: "/locations/", label: "Locations" },
      { href: "/reserve/", label: "Reserve" },
      { href: "/awards-media/", label: "Awards & Media" },
      { href: "/founders/", label: "Founders" },
      { href: "/sustainability/", label: "Sustainability" },
      { href: "/careers/", label: "Careers" },
    ],
  },
  socialLinks: [
    { href: "https://www.instagram.com/", label: "Instagram" },
    { href: "https://www.facebook.com/", label: "Facebook" },
    { href: "https://www.tiktok.com/", label: "TikTok" },
  ],
  reservation: {
    primaryLabel: "Reserve",
    fallbackHref: "/reserve/",
    providers: ["SevenRooms", "OpenTable", "TheFork", "WhatsApp", "Phone", "Email", "Custom URL"],
  },
  locations: [
    {
      slug: "hong-kong",
      name: "Hong Kong",
      han: "香港",
      region: "Asia",
      address: "Standard Chartered Bank Building",
      image: "/assets/loc-hk.jpg",
      status: "open",
      hours: "Lunch and dinner daily",
      phone: "+852 2885 8688",
      email: "{email}",
      reserve: "https://www.sevenrooms.com/reservations/mott32hk",
      reservationProvider: "SevenRooms",
      menuNote: "Full signature menu, wine list and cocktail programme.",
      cuisinePdf: "",
      drinksPdf: "https://mott32.com/fileadmin/content/Hong_Kong/Menu_PDFs/MTHK_Menu_Wine_260309.pdf",
      intro:
        "Located inside the Standard Chartered Bank Building, Hong Kong is the original {brand} and the reference point for the global restaurant family.",
      copy: "A layered dining room, refined cooking and {brand} signatures define the restaurant where the brand began.",
    },
    {
      slug: "singapore",
      name: "Singapore",
      han: "新加坡",
      region: "Asia",
      address: "Marina Bay Sands",
      image: "/assets/loc-singapore.jpg",
      status: "open",
      hours: "Lunch and dinner daily",
      phone: "+65 6688 9922",
      email: "{email}",
      reserve: "https://www.marinabaysands.com/restaurants/mott32/search.html",
      reservationProvider: "Custom URL",
      menuNote: "Marina Bay Sands menus and reservations are handled by the resort.",
      intro: "A dramatic Marina Bay Sands dining room with signature cuisine, cocktails and service rituals.",
      copy: "Singapore brings {brand}'s Cantonese, Beijing and Szechuan influences into one of the city's landmark resorts.",
    },
    {
      slug: "bangkok",
      name: "Bangkok",
      han: "曼谷",
      region: "Asia",
      address: "The Standard Bangkok Mahanakhon",
      image: "/assets/loc-bangkok.jpg",
      status: "open",
      hours: "Dinner daily",
      phone: "+66 2 085 8888",
      email: "{email}",
      reserve:
        "https://www.tablecheck.com/en/shops/the-standard-bangkok-mahanakhon-mott32-bangkok/reserve?utm_source=Website&utm_medium=Brandweb",
      reservationProvider: "Custom URL",
      menuNote: "Bangkok signatures and high-rise dining.",
      intro:
        "Set inside The Standard Bangkok Mahanakhon, this location pairs high-rise views with Cantonese and regional Chinese signatures.",
      copy: "The Bangkok restaurant carries the full {brand} experience into a high-energy dining room above the city.",
    },
    {
      slug: "seoul",
      name: "Seoul",
      han: "首爾",
      region: "Asia",
      address: "Central City",
      image: "/assets/loc-seoul.jpg",
      status: "open",
      hours: "Lunch and dinner daily",
      phone: "+82 2 6282 0320",
      email: "{email}",
      reserve: "https://www.josunhotel.com/resve/dining/step0.do?searchSysCode=JOSUNHOTEL&diningCode=006",
      reservationProvider: "Custom URL",
      menuNote: "Seoul menu and booking are handled by the hotel.",
      intro: "Central City hosts a layered {brand} interior with private dining, rich materials and signature menus.",
      copy: "{brand} Seoul combines warm interiors, private dining and award-winning food and drinks.",
    },
    {
      slug: "cebu",
      name: "Cebu",
      han: "宿霧",
      region: "Asia",
      address: "Nustar Resort",
      image: "/assets/loc-cebu.jpg",
      status: "open",
      hours: "Lunch and dinner daily",
      phone: "+63 32 888 8282",
      email: "{email}",
      reserve: "https://www.opentable.co.uk/r/mott32-cebu-city",
      reservationProvider: "OpenTable",
      menuNote: "Resort dining with signature food and cocktail selections.",
      intro: "A resort setting at Nustar Cebu with a focus on dim sum, barbecue, seafood and cocktails.",
      copy: "Cebu adapts the restaurant's global signatures to a destination resort setting.",
    },
    {
      slug: "las-vegas",
      name: "Las Vegas",
      han: "拉斯維加斯",
      region: "North America",
      address: "The Venetian Resort",
      image: "/assets/loc-vegas.jpg",
      status: "open",
      hours: "Dinner daily",
      phone: "+1 702 607 3232",
      email: "{email}",
      reserve: "https://www.sevenrooms.com/reservations/mott32/brand-website",
      reservationProvider: "SevenRooms",
      menuNote: "Las Vegas reservations are handled through SevenRooms.",
      intro: "Located at The Venetian Resort, Las Vegas combines destination dining, theatrical interiors and signatures.",
      copy: "A richly detailed room for Peking duck, dim sum, cocktails and group dining on the Las Vegas Strip.",
    },
    {
      slug: "vancouver",
      name: "Vancouver",
      han: "溫哥華",
      region: "North America",
      address: "1161 W Georgia Street",
      image: "/assets/loc-vancouver.jpg",
      status: "open",
      hours: "Dinner daily",
      phone: "+1 604 979 8886",
      email: "{email}",
      reserve: "https://www.opentable.ca/r/mott-32-vancouver-2",
      reservationProvider: "OpenTable",
      menuNote: "Vancouver reservations are handled through OpenTable.",
      intro: "The Vancouver restaurant brings the brand's award-winning Chinese cuisine to the centre of the city.",
      copy: "Vancouver combines a polished dining room with signature Cantonese barbecue and dim sum.",
    },
    {
      slug: "toronto",
      name: "Toronto",
      han: "多倫多",
      region: "North America",
      address: "190 University Avenue",
      image: "/assets/loc-toronto.jpg",
      status: "open",
      hours: "Dinner daily",
      phone: "+1 416 555 0032",
      email: "{email}",
      reserve: "https://app.tablz.com/mott-32",
      reservationProvider: "Custom URL",
      menuNote: "Toronto reservations are handled through Tablz.",
      intro: "Toronto carries the global {brand} menu into a polished bar, lounge and restaurant environment.",
      copy: "A city-centre location with a strong bar presence, refined dining and signature menus.",
    },
    {
      slug: "dubai",
      name: "Dubai",
      han: "迪拜",
      region: "Middle East",
      address: "73rd Floor, Address Beach Resort",
      image: "/assets/loc-dubai.jpg",
      status: "open",
      hours: "Lunch and dinner daily",
      phone: "+971 4 278 4832",
      email: "{email}",
      reserve: "https://www.sevenrooms.com/reservations/mott32dubai/ig",
      reservationProvider: "SevenRooms",
      menuNote: "Dubai offers terrace dining, cocktails and skyline views.",
      intro: "{brand} Dubai sits high inside Address Beach Resort with terrace dining and signature food and drinks.",
      copy: "A high-rise dining room and terrace setting for classics, cocktails and skyline views.",
    },
    {
      slug: "los-angeles",
      name: "Los Angeles",
      han: "洛杉磯",
      region: "North America",
      address: "Opening 2026",
      image: "/assets/loc-los-angeles.jpg",
      status: "coming-soon",
      opening: "Opening 2026",
      hours: "Coming soon",
      phone: "",
      email: "{email}",
      reserve: "/reserve/",
      reservationProvider: "Custom URL",
      menuNote: "Menus will be announced closer to opening.",
      intro: "Los Angeles is planned as a forthcoming North American location.",
      copy: "Opening details will follow as the new restaurant approaches launch.",
    },
    {
      slug: "scottsdale",
      name: "Scottsdale",
      han: "斯科茨代爾",
      region: "North America",
      address: "Opening 2026",
      image: "/assets/loc-scottsdale.jpg",
      status: "coming-soon",
      opening: "Opening 2026",
      hours: "Coming soon",
      phone: "",
      email: "{email}",
      reserve: "",
      reservationProvider: "Custom URL",
      menuNote: "Menus will be announced closer to opening.",
      intro: "Scottsdale is planned as a future North American location.",
      copy: "Opening details will follow closer to launch.",
    },
    {
      slug: "bali",
      name: "Bali",
      han: "峇里島",
      region: "Asia",
      address: "Opening 2027",
      image: "/assets/loc-bali.jpg",
      status: "coming-soon",
      opening: "Opening 2027",
      hours: "Coming soon",
      phone: "",
      email: "{email}",
      reserve: "",
      reservationProvider: "Custom URL",
      menuNote: "Menus will be announced closer to opening.",
      intro: "Bali is planned as a future {brand} destination.",
      copy: "Opening details will follow closer to launch.",
    },
    {
      slug: "riyadh",
      name: "Riyadh",
      han: "利雅德",
      region: "Middle East",
      address: "Opening 2027",
      image: "/assets/loc-riyadh.jpg",
      status: "coming-soon",
      opening: "Opening 2027",
      hours: "Coming soon",
      phone: "",
      email: "{email}",
      reserve: "",
      reservationProvider: "Custom URL",
      menuNote: "Menus will be announced closer to opening.",
      intro: "Riyadh is planned as a future Middle East location.",
      copy: "Opening details will follow closer to launch.",
    },
    {
      slug: "melbourne",
      name: "Melbourne",
      han: "墨爾本",
      region: "Australia",
      address: "Opening 2026",
      image: "/assets/loc-melbourne.jpg",
      status: "coming-soon",
      opening: "Opening 2026",
      hours: "Coming soon",
      phone: "",
      email: "{email}",
      reserve: "",
      reservationProvider: "Custom URL",
      menuNote: "Menus will be announced closer to opening.",
      intro: "Melbourne is planned as a future Australian location.",
      copy: "Opening details will follow closer to launch.",
    },
  ],
  menu: {
    items: [
      {
        title: "Applewood Roasted Peking Duck",
        locations: ["hong-kong", "las-vegas", "vancouver", "singapore", "dubai", "bangkok", "seoul"],
        price: "Market price",
        allergens: ["gluten", "soy"],
        dietary: ["signature"],
      },
      {
        title: "Crispy Sugar Coated Peking Duck Bun",
        locations: ["hong-kong", "las-vegas", "vancouver", "dubai", "cebu"],
        price: "€€",
        allergens: ["gluten"],
        dietary: ["signature"],
      },
      {
        title: "Signature Iberico Pluma Char Siu",
        locations: ["hong-kong", "vancouver", "singapore", "dubai", "toronto", "bangkok"],
        price: "€€€",
        allergens: ["soy"],
        dietary: ["signature"],
      },
      {
        title: "Prawn & Crab Claw Dumpling",
        aliases: ["Prawn and Crab Claw Dumpling"],
        locations: ["hong-kong", "las-vegas", "singapore", "dubai", "cebu", "seoul"],
        price: "€€",
        allergens: ["shellfish", "gluten"],
        dietary: ["seafood"],
      },
      {
        title: "Matsutake Mushroom",
        locations: ["hong-kong", "singapore", "dubai", "seoul"],
        price: "Seasonal",
        allergens: [],
        dietary: ["vegetarian", "seasonal"],
      },
      {
        title: "Soft Quail Egg, Iberico Pork, Black Truffle Siu Mai",
        locations: ["hong-kong", "las-vegas", "vancouver", "singapore", "dubai"],
        price: "€€",
        allergens: ["egg", "gluten"],
        dietary: ["dim sum"],
      },
      {
        title: "Hanami",
        locations: ["hong-kong", "las-vegas", "vancouver", "singapore", "dubai", "bangkok"],
        price: "€€",
        allergens: [],
        dietary: ["cocktail"],
      },
      {
        title: "Forbidden Rose",
        locations: ["hong-kong", "las-vegas", "vancouver", "singapore", "dubai", "toronto"],
        price: "€€",
        allergens: [],
        dietary: ["cocktail"],
      },
      {
        title: "Hong Kong Iced Tea",
        locations: ["hong-kong", "vancouver", "singapore", "dubai", "cebu"],
        price: "€€",
        allergens: [],
        dietary: ["tea inspired"],
      },
      {
        title: "Old Harbour",
        locations: ["hong-kong", "las-vegas", "dubai", "bangkok", "seoul"],
        price: "€€",
        allergens: [],
        dietary: ["cocktail"],
      },
      {
        title: "Anna Wong",
        locations: ["hong-kong", "vancouver", "singapore", "toronto"],
        price: "€€",
        allergens: [],
        dietary: ["cocktail"],
      },
      {
        title: "Group Restaurant Champion Wine by the Glass",
        locations: ["hong-kong", "las-vegas", "vancouver", "singapore", "dubai"],
        price: "By glass",
        allergens: ["sulphites"],
        dietary: ["wine"],
      },
      {
        title: "Sake Selection",
        locations: ["hong-kong", "las-vegas", "singapore", "seoul"],
        price: "By glass",
        allergens: [],
        dietary: ["sake"],
      },
      {
        title: "Joe's Elixir",
        locations: ["hong-kong", "las-vegas", "dubai", "toronto"],
        price: "€€",
        allergens: [],
        dietary: ["cocktail"],
      },
    ],
  },
  vip: {
    enabled: true,
    delayMs: 4200,
    scrollRatio: 0.38,
    reopenDays: 7,
    variants: [
      {
        id: "global",
        image: "/assets/vip.jpg",
        eyebrow: "Become",
        title: "A Global VIP",
        copy: "Receive exclusive invitations to events and tastings before everyone else.",
        fieldLabel: "Email",
        cta: "Sign up",
      },
      {
        id: "tastings",
        image: "/assets/cuisine-hero-platter.jpg",
        eyebrow: "Private tastings",
        title: "First access to seasonal menus",
        copy: "Be notified about chef tastings, wine dinners and limited menus across the {brand} family.",
        fieldLabel: "Email",
        cta: "Join the list",
      },
      {
        id: "events",
        image: "/assets/drinks-hero-forbidden.jpg",
        eyebrow: "Cocktails & events",
        title: "Invitations before release",
        copy: "Join the VIP list for cocktail previews, openings and special event announcements.",
        fieldLabel: "Email",
        cta: "Become VIP",
      },
    ],
  },
  seo: {
    baseUrl: "https://restaurant.example.com",
    sameAs: ["https://www.instagram.com/", "https://www.facebook.com/"],
    localBusiness: {
      addressLocality: "Madrid",
      addressRegion: "Madrid",
      addressCountry: "ES",
      postalCode: "28001",
      streetAddress: "Calle Example 1",
    },
    pages: {
      "/": {
        title: "{brand} | Award-winning Restaurant",
        description:
          "Premium restaurant website with signature cuisine, cocktails, wine, design-led dining rooms and reservations.",
        image: "/assets/loc-dubai.jpg",
      },
      "/our-cuisine/": {
        title: "Our Cuisine | {brand}",
        description: "Signature cuisine, seasonal dishes, menus by location and private dining.",
        image: "/assets/cuisine-hero-duck.jpg",
      },
      "/our-drinks/": {
        title: "Our Drinks | {brand}",
        description: "Cocktails, sake selection, wine list and bar experiences by location.",
        image: "/assets/drinks-hero-forbidden.jpg",
      },
      "/locations/": {
        title: "All Locations | {brand}",
        description: "Find restaurant locations, reservation links, opening-soon venues and regional details.",
        image: "/assets/loc-hk.jpg",
      },
      "/reserve/": {
        title: "Reserve | {brand}",
        description: "Choose your restaurant and reserve directly with each location.",
        image: "/assets/reserve-bg.jpg",
      },
      "/awards-media/": {
        title: "Awards & Media | {brand}",
        description: "Awards, media mentions and restaurant recognition.",
        image: "/assets/awards-hero.jpg",
      },
      "/founders/": {
        title: "Founders | {brand}",
        description: "The leadership and hospitality team behind the restaurant group.",
        image: "/assets/founder-matt-reid.jpg",
      },
      "/sustainability/": {
        title: "Sustainability | {brand}",
        description: "Supplier standards, environmental commitments and responsible hospitality.",
        image: "/assets/sustainability-steamer.jpg",
      },
      "/careers/": {
        title: "Careers | {brand}",
        description: "Careers across kitchen, bar, service and restaurant operations.",
        image: "/assets/careers-kitchen.jpg",
      },
      "/privacy-policy/": {
        title: "Privacy Policy | {brand}",
        description: "Privacy policy and data handling for guests and enquiries.",
        image: "/assets/loc-dubai.jpg",
      },
    },
  },
};
